version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.0
    - 1.37.1
    - 1.37.10
    - 1.37.11
    - 1.37.12
    - 1.37.13
    - 1.37.14
    - 1.37.15
    - 1.37.16
    - 1.37.17
    - 1.37.18
    - 1.37.19
    - 1.37.2
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.23
    - 1.37.24
    - 1.37.25
    - 1.37.26
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.3
    - 1.37.30
    - 1.37.31
    - 1.37.5
    - 1.37.6
    - 1.37.7
    - 1.37.8
    - 1.37.9
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.0
    - 1.7.1
    - 1.8.0
